# This file is included due to legacy reasons
# It makes sure that Docker starts the languagetool container for Pro customers
# We will delete this file in July 2025
include:
  - languagetool/docker-compose.yml
